export CLICOLOR=1
export LSCOLORS="ExGxBxDxCxEgEdxbxgxcxd"
export PS1="\[\e[32;1m\]\u@\H\[\033[00m\]:\[\033[01;34m\]\w\[\e[0m\]\$ "

alias vi="mvim -v"

# Setting PATH for Python 2.7
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH
