export CLICOLOR=1
export LSCOLORS="ExGxBxDxCxEgEdxbxgxcxd"

setopt PROMPT_SUBST

parse_git_branch() {
    git branch 2>/dev/null | sed -n 's/^\* / (/p' | sed 's/$/)/'
}

export PROMPT='%B${debian_chroot:+($debian_chroot)}%F{green}%n@%m%f:%F{blue}%~%F{red}$(parse_git_branch)%f$%b '

# keybindings
bindkey '\e[H'    beginning-of-line
bindkey '\e[F'    end-of-line

# Wordchars
WORDCHARS=''

# Path Python3
export PATH="/Users/yfiua/Library/Python/3.9/bin:$PATH"

# Path Homebrew
export PATH="/opt/homebrew/bin:$PATH"

# Path Node.js
export PATH="/opt/homebrew/opt/node@20/bin:$PATH"

## For compilers to find node@20
export LDFLAGS="-L/opt/homebrew/opt/node@20/lib"
export CPPFLAGS="-I/opt/homebrew/opt/node@20/include"
